config/routes.rb
Rails.application.routes.draw do

  get 'productivity/index'

  resources :clarification_types
  get 'home/mensajeAlerta'
  get 'home/par3'
  get 'home/par2'
  get 'home/par1'
  get 'carga_prosas/archivos'
  get 'clarifications/archivos'
  get 'files_clarifications/archivos'

  get 'clarifications/dynamic'

  filter :locale
  resources :clarifications
  resources :states
  resources :carga_prosas
  resources :files_clarifications
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users

  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/controllers/clarification_types_controller.rb
class ClarificationTypesController < ApplicationController
  before_action :set_clarification_type, only: [:show, :edit, :update, :destroy]

  # GET /clarification_types
  # GET /clarification_types.json
  def index
    if current_user
      @cu = current_user.profile_id

      if @cu == 1

        @per = Permission.where("view_name = 'ClarificationTypes' and profile_id = ?", @cu)

        @per.each do |permisos|
          @uno = permisos.view_name
          @crearType = permisos.crear
          @editarType = permisos.editar
          @leerType = permisos.leer
          @eliminarType = permisos.eliminar

          if permisos.view_name == "ClarificationTypes"

            @@crear = permisos.crear
            @@editar = permisos.editar
            @@leer = permisos.leer
            @@eliminar = permisos.eliminar

            @crear = permisos.crear
            @editar = permisos.editar
            @leer = permisos.leer
            @eliminar = permisos.eliminar
          end

        end

        if ((@@crear == 8) || (@@editar == 4) || (@@leer == 2) || (@@eliminar == 1))
          @clarification_types = ClarificationType.where.not(:id => 1).page(params[:page]).per(10)

          if params[:search]
            @name = params[:clarif_name]

            @search= ClarificationType.where("name LIKE ?", "%#{@name}%").where.not(:id => 1).count
            @query = t('all.name') + ' = ' + @name

            if @search == 0
              @error = true
            end

            @clarification_types = ClarificationType.where("name LIKE ?", "%#{@name}%").where.not(:id => 1).page(params[:page]).per(10)
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_access')
        end
      else
        @Without_Permission = 100
        redirect_to home_index_path, :alert => t('all.not_access')
      end
    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end

  # GET /clarification_types/1
  # GET /clarification_types/1.json
  def show
  end

  # GET /clarification_types/new
  def new
    @clarification_type = ClarificationType.new
  end

  # GET /clarification_types/1/edit
  def edit
  end

  # POST /clarification_types
  # POST /clarification_types.json
  def create
    @clarification_type = ClarificationType.new(clarification_type_params)

    respond_to do |format|
      if @clarification_type.save
        format.html { redirect_to clarification_types_path, notice: t('views.clarif_type_index.creted') }
        format.json { render :show, status: :created, location: @clarification_type }
      else
        format.html { render :new }
        format.json { render json: clarification_types_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clarification_types/1
  # PATCH/PUT /clarification_types/1.json
  def update
    respond_to do |format|
      if @clarification_type.update(clarification_type_params)
        format.html { redirect_to clarification_types_path, notice: t('views.clarif_type_index.updated') }
        format.json { render :show, status: :ok, location: @clarification_type }
      else
        format.html { render :edit }
        format.json { render json: clarification_types_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clarification_types/1
  # DELETE /clarification_types/1.json
  def destroy
    @clarification_type.destroy

    @cl = Clarification.where(:clarification_type_id =>  @clarification_type.id)

    if @cl.length > 0
      @cl.each do |c|
        c.clarification_type_id = 1
        c.save
      end
    end
    respond_to do |format|
      format.html { redirect_to clarification_types_url, notice:  t('views.clarif_type_index.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clarification_type
      @clarification_type = ClarificationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clarification_type_params
      params.require(:clarification_type).permit(:name)
    end
end

app/helpers/clarification_types_helper.rb
module ClarificationTypesHelper
end

app/views/clarification_types/_form.html.erb
<%= form_for(clarification_type) do |f| %>
  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-4">

      <% if clarification_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(clarification_type.errors.count, "error") %> prohibited this clarification_type from being
            saved:</h2>
          <ul>
            <% clarification_type.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <label><%= t('all.name') %></label>
        <%= f.text_field :name, :class => 'form-control', :required => true, :id => 'nombre', autocomplete: "off", :maxlength => '255' %>
      </div>
    </div>
    <div class="col-xs-4"></div>
  </div>

  <div class="col-md-12 hr-line-dashed"></div>
  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <button type="submit" , class="btn btn-xs btn-primary " , value="<%= t('all.save') %>" , name="btnSave">
          <i class="fa fa-tags"></i>  <%= t('all.save') %>
        </button>
        <%= link_to '<span class="fa fa-tags" ></span>  '.html_safe + t('all.back'), clarification_types_path, :class => 'btn btn-xs btn-primary dim' %>
      </div>
    </div>
  </div>
<% end %>

app/views/clarification_types/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.clarif_type_edit.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">

        <%= render 'form', clarification_type: @clarification_type %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/clarification_types/index.html.erb
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('table').footable({paginate: false});
    });
</script>

<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('all.types') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <% if @error.present? %>
          <script>
              swal({
                  title: "<%= t('all.no_filter')%>",
                  type: "warning"

              }); // swal
          </script>
        <% end %>

        <%= form_tag({:controller => "clarification_types", :action => "index"}, :method => "get") do %>
          <input type="hidden" value="<%= params[:locale] %>" name="locale">
          <input type="hidden" value="true" name="search">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" class="form-control" name="clarif_name" autocomplete="off" placeholder="<%= t('views.clarif_type_index.name') %>">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <div class="btn-group">
                  <%#= submit_tag t('all.btn_search'), :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>

                  <%= button_tag(type: 'submit', class: 'btn btn-w-m btn-info') do %>
                    <i class="fa fa-search"></i>
                    <%= t('all.btn_search') %>
                  <% end %>
                </div>
              </div>
            </div>

          </div>

        <% end %>

        <% if @query.present? %>

          <div class="row">
            <div class="col-lg-4">
              <h3><%= t('all.query') %>: <%= @query %></h3>
            </div>
            <div class="col-lg-8">
              <div class="row">
                <div class="col-xs-6 col-sm-4">
                  <div class="form-group">
                    <%= link_to t('all.clean'), clarification_types_path, :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        <% end %>


        <div class="row">
          <div class="col-sm-4">
            <br>
            <br>
            <% if @crearType == 8 %>
              <%= link_to '<span class="fa fa-tags"></span> '.html_safe + t('views.areas_index.new'), new_clarification_type_path, :class => 'btn btn-xs btn-info dim' %>
            <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="detall_left">
                <%= page_entries_info @clarification_types, entry_name: t('all.types') %>
              </div>
              <div class="pag_right">
                <%= paginate @clarification_types, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
            </div>
          </div>
        </div>
        <div class="table table-responsive overflow col-sm-3" tabindex="5005" style="overflow: hidden; outline: none;">
          <table class="table footable no-paging" data-filter=#filter data-page-size="10">
            <thead>
            <tr>
              <th class="text-center" data-sort-ignore="true"><%= t('all.name') %></th>
              <% if @editarType == 4 %>
                <th class="text-center" data-sort-ignore="true"><%= t('views.areas_index.edit') %></th>
              <% end %>
              <% if @eliminarType == 1 %>
                <th class="text-center" data-sort-ignore="true"><%= t('views.areas_index.destroy') %></th>
              <% end %>
            </tr>
            </thead>

            <tbody>
            <% @clarification_types.each do |clarification_type| %>
              <tr>
                <td class="text-center"><%= clarification_type.name %></td>
                <% if @editarType == 4 %>
                  <td class="text-center">
                    <%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil "></i></button>'.html_safe, edit_clarification_type_path(clarification_type), :data => {:no_turbolink => false} %>
                  </td>
                <% end %>
                <% if @eliminarType == 1 %>
                  <td class="text-center">
                    <input type="hidden" value="<%= clarification_type.name %>" id="clarif_types<%= clarification_type.id %>">
                    <%#= link_to '<button class="btn btn-danger btn-xs areas" type="button"><i class="fa fa-trash-o "></i></button>'.html_safe, area, method: :delete, data: {confirm: t('views.areas_index.confirm')}, :id => area.id %>
                    <button class="btn btn-danger btn-xs  clarif_types" type="button" id="<%= clarification_type.id %>">
                      <i class="fa fa-trash-o"></i>
                    </button>
                  </td>
                <% end %>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <br>

        <div class="row">
          <div class="col-sm-4">
            <% if @crearType == 8 %>
              <%= link_to '<span class="fa fa-tags"></span> '.html_safe + t('views.areas_index.new'), new_clarification_type_path, :class => 'btn btn-xs btn-info dim' %>

          <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="pag_right">
                <%= paginate @clarification_types, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
              <div class="detall_right">
                <%= page_entries_info @clarification_types, entry_name: t('all.types') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

<script type="text/javascript">
    function checkSubmit() {
        document.getElementById("sub").value = "Sending...";
        document.getElementById("sub").disabled = true;
        return true;
    }

    $(".pop").popover({trigger: "manual", html: true, animation: false})
        .on("mouseenter", function () {
            var _this = this;
            $(this).popover("show");
            $(".popover").on("mouseleave", function () {
                $(_this).popover('hide');
            });
        }).on("mouseleave", function () {
        var _this = this;
        setTimeout(function () {
            if (!$(".popover:hover").length) {
                $(_this).popover("hide");
            }
        }, 300);
    });

    $("[data-toggle=hover]").popover({html: true})
    $('#popoverData').popover();
    /*$(document).ready(function () {
     $('table').footable();
     });*/

    <% if @eliminarType == 1 %>
    function recargar() {
        window.location.reload(true);
    }

    $(document).on("click", ".clarif_types", function () {
        var id = this.id;
        var type = $("#clarif_types" + id).val();
        swal({
                title: '<%= t('views.mess_apli_title')%>  ' + '<%= t('views.clarif_type_index.type')%>  ' + type + '?',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<%= t('views.mess_apli_swall_confirm')%> ",
                cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                closeOnConfirm: false,
                closeOnCancel: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal({
                            title: '<%= t('views.clarif_type_index.confirm2')%>',
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "<%= t('views.mess_apli_swall_confirm')%> ",
                            cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.ajax({
                                    type: "POST",
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                                    },
                                    url: "/clarification_types/" + id,
                                    data: {"_method": "delete"},
                                })
                                swal(
                                    {
                                        title: '<%= t('views.mess_apli_swall')%>',
                                        type: "success",
                                        confirmButtonText: "OK",
                                    }, function (isConfirm) {
                                        if (isConfirm) {
                                            recargar();
                                        }
                                    })
                            } else {
                                swal("<%= t('views.mess_apli_swall_cancel_1')%>");
                            }
                        })
                } else {
                    swal("<%= t('views.mess_apli_swall_cancel_1')%>");
                }
            });
    })
    <% end %>


</script>

app/views/clarification_types/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.clarif_type_new.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">

        <%= render 'form', clarification_type: @clarification_type %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/clarification_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @clarification_type.name %>
</p>

<%= link_to 'Edit', edit_clarification_type_path(@clarification_type) %> |
<%= link_to 'Back', clarification_types_path %>